/**
 * WOW-03 — one-click engineering report.
 * Generates a standalone, print-optimized HTML document (open → Ctrl+P for
 * PDF) and a Word-compatible .doc download (Word opens HTML natively).
 * PowerPoint export: deferred to v2 (needs a pptx writer — logged honestly).
 */
import type { LineConfig, RecorderReport, SimulationSnapshot } from '@dtp/engine';
import type { StoryLine } from './story.js';
import { defById } from './machines.js';

const pct = (x?: number) => x === undefined ? '—' : `${(x * 100).toFixed(1)} %`;

export function buildReportHtml(
  cfg: LineConfig, rep: RecorderReport, snap: SimulationSnapshot,
  story: StoryLine[], applied: string[],
): string {
  const sink = snap.machines.find(m => m.archetype === 'sink');
  const tput = sink && rep.elapsed > 0 ? (sink.count / rep.elapsed) * 60 : 0;
  const bot = rep.machines.find(m => m.id === rep.bottleneck);

  const machineRows = cfg.machines.map(m => {
    const def = defById((m as { definitionId?: string }).definitionId ?? guessDef(m.id));
    const params = Object.entries(m.params)
      .map(([k, v]) => `${k} = ${v}`).join(', ');
    const r = rep.machines.find(x => x.id === m.id);
    return `<tr><td><b>${m.id}</b> ${def.name}</td><td>${m.archetype}</td>
      <td>${params || '—'}</td><td>${r ? pct(r.oee?.value) : '—'}</td></tr>`;
  }).join('');

  const oeeRows = bot ? `
    <tr><td>Availability</td><td>${pct(bot.availability?.value)}</td><td>${bot.availability?.formula ?? ''}</td></tr>
    <tr><td>Performance</td><td>${pct(bot.performance?.value)}</td><td>${bot.performance?.formula ?? ''}</td></tr>
    <tr><td>Quality</td><td>${pct(bot.quality?.value)}</td><td>${bot.quality?.formula ?? ''}</td></tr>
    <tr><td><b>OEE</b></td><td><b>${pct(bot.oee?.value)}</b></td><td>${bot.oee?.formula ?? ''}</td></tr>` : '';

  const storyHtml = story.map(s =>
    `<div style="margin-left:${s.depth * 22}px" class="${s.depth ? 'why' : 'lead'}">${s.depth ? '↳ ' : ''}${s.text}</div>`,
  ).join('');

  return `<!-- engineering report -->
<meta charset="utf-8">
<title>Engineering Report — ${cfg.name}</title>
<style>
  body { font: 13px/1.55 system-ui, sans-serif; color: #111; max-width: 800px; margin: 30px auto; padding: 0 20px; }
  h1 { font-size: 21px; margin-bottom: 2px; } h2 { font-size: 15px; margin: 22px 0 8px; border-bottom: 1px solid #ddd; padding-bottom: 4px; }
  .meta { color: #666; font-size: 11px; margin-bottom: 18px; }
  table { width: 100%; border-collapse: collapse; font-size: 12px; }
  th { text-align: left; border-bottom: 2px solid #333; padding: 5px 8px; } td { border-bottom: 1px solid #e5e5e5; padding: 5px 8px; vertical-align: top; }
  .kpis { display: flex; gap: 14px; margin: 12px 0; }
  .kpi { border: 1px solid #ddd; border-radius: 8px; padding: 8px 14px; }
  .kpi .k { font-size: 10px; color: #666; } .kpi .v { font-size: 19px; font-weight: 700; }
  .lead { font-weight: 600; margin: 8px 0 4px; } .why { color: #333; margin: 3px 0; }
  .foot { margin-top: 26px; color: #888; font-size: 10px; border-top: 1px solid #ddd; padding-top: 8px; }
  .noprint { background:#eef4ff; border:1px solid #bcd; border-radius:8px; padding:8px 12px; margin-bottom:16px; font-size:12px; }
  @media print { .noprint { display: none; } }
</style>
<div class="noprint">Press <b>Ctrl/Cmd + P</b> to save as PDF. This document is self-contained.</div>
<h1>Engineering Report — ${cfg.name}</h1>
<div class="meta">Generated by DTP Digital Twin Platform · simulated ${rep.elapsed.toFixed(0)} s · seed ${cfg.seed}
 (deterministic: this seed reproduces every number below bit-exactly)${applied.length ? ` · applied improvements: ${applied.join('; ')}` : ''}</div>

<div class="kpis">
  <div class="kpi"><div class="k">Line throughput</div><div class="v">${tput.toFixed(1)} ppm</div></div>
  <div class="kpi"><div class="k">Constraint (bottleneck)</div><div class="v">${rep.bottleneck ?? '—'}</div></div>
  <div class="kpi"><div class="k">OEE @ constraint</div><div class="v">${pct(bot?.oee?.value)}</div></div>
  <div class="kpi"><div class="k">Good / total @ constraint</div><div class="v">${bot ? `${bot.goodCount} / ${bot.totalCount}` : '—'}</div></div>
</div>

<h2>Why — causal analysis (Engineering Story)</h2>
${storyHtml}

<h2>OEE decomposition @ ${rep.bottleneck ?? '—'} (transparent calculations)</h2>
<table><tr><th>Component</th><th>Value</th><th>Formula</th></tr>${oeeRows}</table>

<h2>Line configuration</h2>
<table><tr><th>Machine</th><th>Archetype</th><th>Parameters (SI)</th><th>OEE</th></tr>${machineRows}</table>

<h2>Assumptions & conventions</h2>
<ul style="font-size:12px">
  <li>Starved/blocked time is attributed to Performance, not Availability (company OEE standard).</li>
  <li>All values in SI units internally; ppm = pieces per minute (display).</li>
  <li>Deterministic simulation: identical project + seed ⇒ identical results on any machine.</li>
</ul>
<div class="foot">DTP Engineering Digital Twin Platform · no black boxes: every value above carries its formula.</div>`;
}

/** map instance id prefix back to a definition (v0.1 helper) */
function guessDef(instanceId: string): string {
  const prefix = instanceId.split('-')[0];
  const map: Record<string, string> = {
    IN: 'infeed', CV: 'belt-conveyor', TO: 'tunnel-oven', CS: 'cooling-conveyor',
    FW: 'flow-wrapper', CW: 'checkweigher', BF: 'buffer-table', CP: 'case-packer', SK: 'palletizing',
  };
  return map[prefix ?? ''] ?? 'belt-conveyor';
}

export function downloadDoc(html: string, name: string): void {
  // Word opens HTML documents natively; .doc extension routes it there.
  const blob = new Blob(['﻿' + html], { type: 'application/msword' });
  trigger(blob, `${name}.doc`);
}
export function downloadHtml(html: string, name: string): void {
  trigger(new Blob([html], { type: 'text/html' }), `${name}.html`);
}
export function downloadJson(obj: unknown, name: string): void {
  trigger(new Blob([JSON.stringify(obj, null, 2)], { type: 'application/json' }), `${name}.json`);
}
function trigger(blob: Blob, filename: string): void {
  const a = document.createElement('a');
  a.href = URL.createObjectURL(blob);
  a.download = filename;
  a.click();
  setTimeout(() => URL.revokeObjectURL(a.href), 5000);
}
